version: "3.9"

services:
  api:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    ports:
      - "${APP_PORT}:8000"
    env_file:
        - .env
    container_name: photos-app-backend
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    stdin_open: true
    tty: true
  db:
    image: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped
    container_name: photos-app-database
volumes:
    postgres_data: