# Generated by Django 5.1.7 on 2025-03-25 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photocollaboration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='photocollaboration',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photocollaboration',
            name='shared_by',
        ),
        migrations.RemoveField(
            model_name='photocollaboration',
            name='shared_with',
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('PHOTO', 'Photo'), ('ALBUM', 'Album')], max_length=5)),
                ('permission', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit')], default='VIEW', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='photos.album')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='photos.photo')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_items', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shared_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AlbumCollaboration',
        ),
        migrations.DeleteModel(
            name='PhotoCollaboration',
        ),
        migrations.AddConstraint(
            model_name='collaboration',
            constraint=models.UniqueConstraint(condition=models.Q(('content_type', 'PHOTO'), ('photo__isnull', False)), fields=('shared_with', 'photo'), name='unique_photo_collaboration'),
        ),
        migrations.AddConstraint(
            model_name='collaboration',
            constraint=models.UniqueConstraint(condition=models.Q(('album__isnull', False), ('content_type', 'ALBUM')), fields=('shared_with', 'album'), name='unique_album_collaboration'),
        ),
        migrations.AddConstraint(
            model_name='collaboration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('album__isnull', True), ('content_type', 'PHOTO'), ('photo__isnull', False)), models.Q(('album__isnull', False), ('content_type', 'ALBUM'), ('photo__isnull', True)), _connector='OR'), name='content_type_consistency'),
        ),
    ]
